<?xml version="1.0"?>
<robot name="simple_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- 기본 파라미터 -->
  <xacro:property name="wheel_radius" value="0.033"/>
  <xacro:property name="wheel_width" value="0.025"/>
  <xacro:property name="body_length" value="0.125"/> <!-- X-axis length: 12.5 cm -->
  <xacro:property name="body_width"  value="0.115"/> <!-- Y-axis width: 11.5 cm -->
  <xacro:property name="body_height" value="0.08"/>  <!-- Z-axis height: 8 cm -->
  <xacro:property name="wheel_base" value="0.08"/> <!-- 앞뒤 바퀴 간격 -->

  <!-- ===================== base_link ===================== -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <origin xyz="0 0 ${body_height/2}" rpy="0 0 0"/>
      <material name="Gray">
        <color rgba="0.6 0.6 0.6 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- ===================== Left Wheels ===================== -->
  <!-- Left Front Wheel -->
  <link name="left_front_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <material name="Black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
  </link>
  <joint name="left_front_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_front_wheel_link"/>
    <origin xyz="${wheel_base/2} ${body_width/2 + wheel_width/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Left Rear Wheel -->
  <link name="left_rear_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <material name="Black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
  </link>
  <joint name="left_rear_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_rear_wheel_link"/>
    <origin xyz="-${wheel_base/2} ${body_width/2 + wheel_width/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- ===================== Right Wheels ===================== -->
  <!-- Right Front Wheel -->
  <link name="right_front_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <material name="Black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
  </link>
  <joint name="right_front_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_front_wheel_link"/>
    <origin xyz="${wheel_base/2} -${body_width/2 + wheel_width/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Right Rear Wheel -->
  <link name="right_rear_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <material name="Black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
  </link>
  <joint name="right_rear_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_rear_wheel_link"/>
    <origin xyz="-${wheel_base/2} -${body_width/2 + wheel_width/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- ===================== Ultrasonic Sensor ===================== -->
  <link name="ultrasonic_link">
    <visual>
      <geometry>
        <box size="0.02 0.05 0.02"/>
      </geometry>
      <origin xyz="${(body_length/2) + 0.01} 0 ${body_height/4}" rpy="0 0 0"/>
      <material name="Yellow">
        <color rgba="1.0 1.0 0.0 1.0"/>
      </material>
    </visual>
  </link>
  <joint name="ultrasonic_link" type="fixed">
    <parent link="base_link"/>
    <child link="ultrasonic_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- ===================== Camera ===================== -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.02 0.05 0.04"/>
      </geometry>
      <origin xyz="${(body_length/2) + 0.01} 0 ${body_height*0.7}" rpy="0 0 0"/>
      <material name="Red">
        <color rgba="1.0 0.0 0.0 1.0"/>
      </material>
    </visual>
  </link>
  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

</robot>
