<?xml version="1.0"?>
<robot name="simple_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ê¸°ë³¸ íŒŒë¼ë¯¸í„° -->
  <xacro:property name="wheel_radius" value="0.033"/>
  <xacro:property name="wheel_width" value="0.025"/>
  <xacro:property name="body_length" value="0.125"/> <!-- X-axis length: 12.5 cm -->
  <xacro:property name="body_width"  value="0.115"/> <!-- Y-axis width: 11.5 cm -->
  <xacro:property name="body_height" value="0.08"/>  <!-- Z-axis height: 8 cm -->
  <xacro:property name="wheel_base" value="0.08"/> <!-- ì•ë’¤ ë°”í€´ ê°„ê²© -->

  <!-- ===================== base_link ===================== -->
  <link name="base_link">
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.001" iyy="0.001" izz="0.001"
              ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
    <visual>
      <geometry> 
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <origin xyz="0 0 ${wheel_radius + body_height/2}" rpy="0 0 0"/>
      <material name="Gray">
        <color rgba="0.6 0.6 0.6 1.0"/>
      </material>
    </visual>
    <collision name="base_collision">
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <origin xyz="0 0 ${wheel_radius + body_height/2}" rpy="0 0 0"/>
    </collision>
  </link>

  <!-- ===================== Left Wheels ===================== -->
  <!-- Left Front Wheel -->
  <link name="left_front_wheel_link">
    <inertial>
      <mass value="0.2"/>  <!-- ì§ˆëŸ‰ (kg) -->
      <inertia 
        ixx="0.000056" iyy="0.000056" izz="0.00009"
        ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <material name="Black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <!-- ğŸ’¡ ë¬¼ë¦¬ ì¶©ëŒ í˜•íƒœ ì¶”ê°€ -->
    <collision name="left_front_wheel_collision">
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>  <!-- visualê³¼ ë™ì¼í•œ íšŒì „ ì ìš© -->
    </collision>
  </link>
  <joint name="left_front_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_front_wheel_link"/>
    <origin xyz="${wheel_base/2} ${body_width/2 + wheel_width/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Left Rear Wheel -->
  <link name="left_rear_wheel_link">
    <inertial>
      <mass value="0.2"/>  <!-- ì§ˆëŸ‰ (kg) -->
      <inertia 
        ixx="0.000056" iyy="0.000056" izz="0.00009"
        ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <material name="Black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision name="left_rear_wheel_collision">
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>  <!-- visualê³¼ ë™ì¼í•œ íšŒì „ ì ìš© -->
    </collision>
  </link>
  <joint name="left_rear_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_rear_wheel_link"/>
    <origin xyz="-${wheel_base/2} ${body_width/2 + wheel_width/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- ===================== Right Wheels ===================== -->
  <!-- Right Front Wheel -->
  <link name="right_front_wheel_link">
    <inertial>
      <mass value="0.2"/>  <!-- ì§ˆëŸ‰ (kg) -->
      <inertia 
        ixx="0.000056" iyy="0.000056" izz="0.00009"
        ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <material name="Black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision name="right_front_wheel_collision">
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>  <!-- visualê³¼ ë™ì¼í•œ íšŒì „ ì ìš© -->
    </collision>
  </link>
  <joint name="right_front_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_front_wheel_link"/>
    <origin xyz="${wheel_base/2} -${body_width/2 + wheel_width/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Right Rear Wheel -->
  <link name="right_rear_wheel_link">
    <inertial>
      <mass value="0.2"/>  <!-- ì§ˆëŸ‰ (kg) -->
      <inertia 
        ixx="0.000056" iyy="0.000056" izz="0.00009"
        ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <material name="Black">
        <color rgba="0 0 0 1"/>
      </material>
    <collision name="right_rear_wheel_collision">
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>  <!-- visualê³¼ ë™ì¼í•œ íšŒì „ ì ìš© -->
    </collision>
    </visual>
  </link>
  <joint name="right_rear_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_rear_wheel_link"/>
    <origin xyz="-${wheel_base/2} -${body_width/2 + wheel_width/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- ===================== Ultrasonic Sensor ===================== -->
  <link name="ultrasonic_link">
    <visual>
      <geometry>
        <box size="0.02 0.05 0.02"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>  <!-- ìê¸° ì¤‘ì‹¬ -->
      <material name="Yellow">
        <color rgba="1.0 1.0 0.0 1.0"/>
      </material>
    </visual>
  </link>
  <!-- <gazebo reference="ultrasonic_link">
    <sensor name="ultrasonic_sensor" type="ray">
      <update_rate>10</update_rate>
      <ray>
        <range>
          <min>0.02</min>
          <max>2.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_range" filename="libgazebo_ros_range.so">
        <ros>
          <namespace>/</namespace>
          <remapping>~/out:=/ultrasonic/data</remapping>
        </ros>
      </plugin>
    </sensor>
  </gazebo> -->
  <joint name="ultrasonic_joint" type="fixed">
    <parent link="base_link"/>
    <child link="ultrasonic_link"/>
    <origin xyz="${(body_length/2) + 0.01} 0 ${body_height/4 + 0.02}" rpy="0 0 0"/>
  </joint>

  <!-- ===================== Camera ===================== -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.02 0.05 0.04"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>  <!-- ìê¸° ì¤‘ì‹¬ -->
      <material name="Red">
        <color rgba="1.0 0.0 0.0 1.0"/>
      </material>
    </visual>
  </link>
  <!-- <gazebo reference="camera_link">
    <sensor name="camera_sensor" type="camera">
      <camera>
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.05</near>
          <far>5.0</far>
        </clip>
      </camera>
      <always_on>true</always_on>
      <update_rate>30</update_rate>
      <plugin name="gazebo_ros_camera" filename="libgazebo_ros_camera.so">
        <ros>
          <namespace>/</namespace>
          <remapping>~/image_raw:=/camera/image_raw</remapping>
        </ros>
      </plugin>
    </sensor>
  </gazebo> -->
  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${(body_length/2) + 0.01} 0 ${body_height*0.7  + 0.02}" rpy="0 0 0"/>
  </joint>

</robot>
