<?xml version="1.0"?>
<robot name="simple_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ===================== 파라미터 ===================== -->
  <xacro:property name="wheel_radius" value="0.033"/>
  <xacro:property name="wheel_width" value="0.025"/>
  <xacro:property name="body_length" value="0.125"/>
  <xacro:property name="body_width" value="0.115"/>
  <xacro:property name="body_height" value="0.08"/>
  <xacro:property name="wheel_base" value="0.08"/>

  <!-- ===================== Base Link ===================== -->
  <link name="base_link">
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.001" iyy="0.001" izz="0.001" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <origin xyz="0 0 ${wheel_radius + body_height/2}" rpy="0 0 0"/>
      <material name="Gray">
        <color rgba="0.6 0.6 0.6 1.0"/>
        <!-- Gazebo에서 동일하게 보이도록 추가 -->
        <ambient>0.6 0.6 0.6 1.0</ambient>
        <diffuse>0.6 0.6 0.6 1.0</diffuse>
        <specular>0.1 0.1 0.1 1.0</specular>
        <emissive>0.0 0.0 0.0 1.0</emissive>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <origin xyz="0 0 ${wheel_radius + body_height/2}" rpy="0 0 0"/>
    </collision>
  </link>

  <!-- ===================== Wheels ===================== -->
  <xacro:macro name="wheel_link" params="wheel_name x y">
    <link name="${wheel_name}_link">
      <inertial>
        <mass value="0.2"/>
        <inertia ixx="0.000056" iyy="0.000056" izz="0.00009" ixy="0.0" ixz="0.0" iyz="0.0"/>
      </inertial>
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <material name="Black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      </collision>
    </link>
    <joint name="${wheel_name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${wheel_name}_link"/>
      <origin xyz="${x} ${y} ${wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Left Wheels -->
  <xacro:wheel_link wheel_name="left_front_wheel" x="${wheel_base/2}" y="${body_width/2 + wheel_width/2}"/>
  <xacro:wheel_link wheel_name="left_rear_wheel" x="-${wheel_base/2}" y="${body_width/2 + wheel_width/2}"/>

  <!-- Right Wheels -->
  <xacro:wheel_link wheel_name="right_front_wheel" x="${wheel_base/2}" y="-${body_width/2 + wheel_width/2}"/>
  <xacro:wheel_link wheel_name="right_rear_wheel" x="-${wheel_base/2}" y="-${body_width/2 + wheel_width/2}"/>

  <!-- ===================== Ultrasonic Sensor ===================== -->
  <link name="ultrasonic_link">
    <visual>
      <geometry>
        <box size="0.02 0.05 0.02"/>
      </geometry>
      <material name="Yellow">
        <color rgba="1 1 0 1"/>
      </material>
    </visual>
  </link>
  <joint name="ultrasonic_joint" type="fixed">
    <parent link="base_link"/>
    <child link="ultrasonic_link"/>
    <origin xyz="${(body_length/2) + 0.01} 0 ${body_height/4 + 0.02}" rpy="0 0 0"/>
  </joint>

  <!-- ===================== Camera ===================== -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.02 0.05 0.04"/>
      </geometry>
      <material name="Red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
  </link>
  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${(body_length/2) + 0.01} 0 ${body_height*0.7 + 0.02}" rpy="0 0 0"/>
  </joint>

  <!-- ros2_control plugin for Ignition Gazebo -->
  <gazebo>
    <!-- Gazebo 플러그인 정의 -->
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <ros2_control>
        <joint name="left_front_wheel_joint"/>
        <joint name="right_front_wheel_joint"/>
        <joint name="left_rear_wheel_joint"/>
        <joint name="right_rear_wheel_joint"/>
      </ros2_control>
    </plugin>
  </gazebo>
</robot>
